version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - "3030:3000"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ai-backend

  ai-backend:
    build: ./backend
    volumes:
      - ./backend/config.json:/app/config.json:rw
    environment:
      - PASSWORD="password"